# Generated by Django 6.0.2 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("bio", models.TextField()),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female")], max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("books", models.ManyToManyField(blank=True, related_name="authors", to="books.book")),
            ],
        ),
    ]
